# Configuration tables for generating star systems
---
auDistanceIncrement:  500.0
auDistanceMap:
  1:  0.02857
  2:  0.07143
  3:  0.14286
  4:  0.28571
  5:  0.57143
  6:  1.0
  7:  1.2
  8:  1.5
  9:  2.0
  10: 3.0
  11: 4.0
  12: 5.0
  13: 6.0
  14: 7.0
  15: 8.0
  16: 9.0
  17: 10.0
  18: 11.0
  19: 12.0
  20: 13.0
  21: 14.0
  22: 15.0
  23: 16.0
  24: 17.0
  25: 20.0
  26: 25.0
  27: 30.0
  28: 35.0
  29: 40.0
  30: 45.0
  31: 50.0
  32: 75.0
  33: 100.0
  34: 150.0
  35: 200.0
  36: 300.0
  37: 500.0
  38: 600.0
  39: 700.0
  40: 800.0
  41: 900.0
  42: 1000.0
  43: 1200.0
  44: 1400.0
  45: 1600.0
  46: 1800.0
  47: 2000.0

starNamesPt1:
  11: Alpha
  12: Beta
  13: Gamma
  14: Delta
  15: Epsilon
  16: Zeta
  21: Nu
  22: Xi
  23: Omicron
  24: Pi
  25: Rho
  26: Sigma
  31: Eta
  32: Theta
  33: Iota
  34: Kappa
  35: Lambda
  36: Mu
  41: Tau
  42: Upsilon
  43: Phi
  44: Chi
  45: Psi
  46: Omega
  51: 51
  52: 52
  53: 53
  54: 54
  55: 55
  56: 56
  61: 61
  62: 62
  63: 63
  64: 64
  65: 65
  66: 66

starNamesPt2a:
  11: Andromedae
  12: Arietis
  13: Canis
  14: Ceti
  15: Corvi
  16: Draconis
  21: Antliae
  22: Aurigae
  23: Capricorni
  24: Chamaeleontis
  25: Crateris
  26: Equulei
  31: Apodis
  32: Carinae
  33: Circini
  34: Crucis
  35: Eridani
  36: Aquarri
  41: Caeli
  42: Cameleopardalis
  43: Columbae
  44: Cygni
  45: Fornacis
  46: Aquilae
  51: Cancri
  52: Casseiopeiae
  53: Comae
  54: Delphini
  55: Geminorum
  56: Arae
  61: Canum
  62: Cantauri
  63: Coronae
  64: Doradus
  65: Gruis
  66: Bootis

starNamesPt2b:
  11: Herculis
  12: Leonis
  13: Mensae
  14: Ophiuchi
  15: Pictoris
  16: Sagittae
  21: Horologii
  22: Leporis
  23: Microscopi
  24: Orionis
  25: Piscium
  26: Sagittarii
  31: Hydrae
  32: Librae
  33: Monocerotis
  34: Pavonis
  35: Piscis
  36: Scorpii
  41: Hydrii
  42: Lupi
  43: Muscae
  44: Pegasi
  45: Puppis
  46: Sculptoris
  51: Indi
  52: Lyncis
  53: Normae
  54: Persei
  55: Pyxidis
  56: Scuti
  61: Lacaertae
  62: Lyrae
  63: Octanis
  64: Phoenicis
  65: Reticuli
  66: Serpentis

starNamesPt2c:
  11: Sextantis
  12: Velorum
  13: Currin
  14: Albellis
  15: Orci
  16: Sentium
  21: Tauri
  22: Virginis
  23: Bathis
  24: Detectum
  25: Bakris
  26: Vulcanis
  31: Telescopi
  32: Volantis
  33: Martius
  34: Salimanis
  35: Capaldum
  36: Kirkalis
  41: Trianguli
  42: Vulpeculae
  43: Caesarus
  44: Christis
  45: Patris
  46: Picardum
  51: Tucanae
  52: Hawkinus
  53: Janjus
  54: Medusi
  55: Russum
  56: Siskum
  61: Ursae
  62: Kentis
  63: Adricus
  64: Vampri
  65: Bondi
  66: Solaris
